#trying few different data types
#more examples at https://github.com/marzer/tomlplusplus/blob/master/examples/example.toml
pi=3.14159
bool=true

#You can indent as you please. Tabs or spaces.
#using substructure as example
[banks]
name = "banks, using substructure as example"

    [banks.names]
    all_banks = ["REC::Particle","REC::Calorimeter"]

[filter]
pids = [ 11, 211, -211 ]

[frame]
type="mirror"