algorithm:
  name: 'clas12::ZVertexFilter'

actions:
  - name: PrepareEvent
    type: creator
    inputs:
      - name: runnum
        type: int
      - name: thread_id
        type: concurrent_key_t
        cast: int
    outputs:
      - type: concurrent_key_t
        cast: int
  - name: Filter
    type: filter
    inputs:
      - name: zvertex
        type: double
      - name: pid
        type: int
      - name: status
        type: int
      - name: key
        type: concurrent_key_t
        cast: int
