algorithm:
  name: 'clas12::ZVertexFilter'

actions:
  - name: Filter
    type: filter
    inputs:
      - name: zvertex
        type: double
      - name: pid
        type: int
      - name: status
        type: int
      - name: key
        type: concurrent_key_t
        cast: int
