# Cut values for different run periods
clas12::ZVertexFilter:

  # scattered electron cuts
  electron:

    # default cuts
    - default:
      vz: [ -15.0, 15.0 ]

    # RG-A fall2018 inbending
    - runs: [ 4760, 5419 ]
      vz: [ -5.0, 3.0 ]

    # RG-A fall2018 outbending
    - runs: [ 5420, 5674 ]
      vz: [ -8.0, 7.0 ]
