# Cut values for different run periods
clas12::ZVertexFilter:

  # NOTE: you can set the log level from the configuration file
  log: trace

  # FIXME: with the addition of `log`, this is now
  # now a proper YAML file; the list below should be put
  # in their own separate node

  # default cuts
  - default:
    electron_vz: [ -1.5, 1.3 ]

  # RG-A fall2018 inbending
  - runs: [ 4760, 5419 ]
    electron_vz: [ -0.5, 0.5 ]

  # RG-A fall2018 outbending
  - runs: [ 5420, 5674 ]
    electron_vz: [ -0.8, 0.7 ]
