# Cut values for different run periods
clas12::ZVertexFilter:

  ###################################################################################
  # NOTE: for convenience, you can also set the log level from the configuration file
  log: trace
  ###################################################################################

  # scattered electron cuts
  electron:

    # default cuts
    - default:
      vz: [ -1.5, 1.3 ]

    # RG-A fall2018 inbending
    - runs: [ 4760, 5419 ]
      vz: [ -0.5, 0.5 ]

    # RG-A fall2018 outbending
    - runs: [ 5420, 5674 ]
      vz: [ -0.8, 0.7 ]
