algorithm:
  name: 'physics::InclusiveKinematics'

actions:
  - name: PrepareEvent
    type: creator
    inputs:
      - name: runnum
        type: int
      - name: thread_id
        type: concurrent_key_t
        cast: int
    outputs:
      - type: concurrent_key_t
        cast: int
  - name: ComputeFromLepton
    type: creator
    inputs:
      - name: lepton_px
        type: double
        cast: float
      - name: lepton_py
        type: double
        cast: float
      - name: lepton_pz
        type: double
        cast: float
      - name: key
        type: concurrent_key_t
        cast: int
    outputs:
      - name: qx
        type: double
      - name: qy
        type: double
      - name: qz
        type: double
      - name: qE
        type: double
      - name: Q2
        type: double
      - name: x
        type: double
      - name: y
        type: double
      - name: W
        type: double
      - name: nu
        type: double
