physics::InclusiveKinematics:

  initial_state:
    - default:
      beam_direction: [ 0.0, 0.0, 1.0 ]
      beam_particle: electron
      target_particle: proton

  method:
    reconstruction: scattered_lepton
    lepton_finder: highest_energy_FD_trigger
