algorithm:
  name: 'clas12::MomentumCorrection'

actions:

  - name: Transform
    type: transformer
    inputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: sec
        type: int
      - name: pid
        type: int
      - name: torus
        type: float
    outputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float

  - name: CorrectionInbending
    type: creator
    inputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: sec
        type: int
      - name: pid
        type: int
    output: double

  - name: CorrectionOutbending
    type: creator
    inputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: sec
        type: int
      - name: pid
        type: int
    output: double

  - name: EnergyLossInbending
    type: creator
    inputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: pid
        type: int
    output: double

  - name: EnergyLossOutbending
    type: creator
    inputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: pid
        type: int
    output: double
