clas12::RGAFiducialFilter:
  calorimeter:
    # Default strictness if not overridden programmatically via SetStrictness(1|2|3)
    # s=1 -> lv,lw >=  9.0 cm
    # s=2 -> lv,lw >= 13.5 cm
    # s=3 -> lv,lw >= 18.0 cm
    #
    # s=1 loosely recommended for spin-asymmetries
    strictness: 1  # scalar is fine; GetOptionVector reads it as [1]

  forward_tagger:
    # Allowed radial window (cm)
    radius: [8.5, 15.5]
    # Circular holes (radius, x, y) 
    holes_flat:
      [ 1.60, -8.42,  9.89,
        1.60, -9.89, -5.33,
        2.30, -6.15, -13.00,
        2.00,  3.70, -6.50 ]

  cvt:
    # Layers to apply the edge>edge_min test to (all). Missing layers are treated as pass.
    edge_layers: [1, 3, 5, 7, 12]
    # edge > 0 to ensure tracks inside CVT
    edge_min: 0.0
    # Forbidden phi wedges in degrees (open intervals). 
    # Example: (25,40), (143,158), (265,280)
    phi_forbidden_deg: [25, 40, 143, 158, 265, 280]

  dc:
    # Theta boundary (degrees) for the special inbending case
    theta_small_deg: 10.0
    # Outbending thresholds [Region1, Region2, Region3] (cm)
    thresholds_out: [3.0, 3.0, 10.0]
    # Inbending thresholds when theta < theta_small_deg (cm)
    thresholds_in_smallTheta: [10.0, 10.0, 10.0]
    # Inbending thresholds when theta >= theta_small_deg (cm)
    thresholds_in_largeTheta: [3.0, 3.0, 10.0]