clas12::RGAFiducialFilter:
  calorimeter:
    # Default strictness if not overridden programmatically via SetStrictness(1|2|3)
    # s=1 -> lv,lw >=  9.0 cm
    # s=2 -> lv,lw >= 13.5 cm
    # s=3 -> lv,lw >= 18.0 cm
    strictness: [1]

  forward_tagger:
    # Allowed radial window (cm)
    radius: [8.5, 15.5]

    # Circular holes (radius, cx, cy) flattened
    holes_flat:
      [ 1.60, -8.42,  9.89,
        1.60, -9.89, -5.33,
        2.30, -6.15, -13.00,
        2.00,  3.70, -6.50 ]