clas12::RGAFiducialFilter:
  # Strictness: 1 (loose), 2, 3 (tight)
  strictness: [3]

  # Forward tagger window and circular holes
  ft_radius: [8.5, 15.5]
  ft_holes_flat: [1.60, -8.42, 9.89,
                  1.60, -9.89, -5.33,
                  2.30, -6.15, -13.00,
                  2.00,  3.70, -6.50]

  # Dead-PMT / exclusion windows as a **flat list**:
  # [sector, layer, axis, low, high, ...]
  # layer: 1=PCAL, 4=ECIN, 7=ECOUT
  # axis:  0=lv,   1=lw,   2=lu
  cal_masks_flat: [
    1, 1, 1,  72.0,  94.5,
    1, 1, 1, 220.5, 234.0,
    1, 4, 0,  67.5,  94.5,
    1, 7, 0,   0.0,  40.5,
    2, 1, 0,  99.0, 117.0,
    2, 1, 0,  31.5,  49.5,
    3, 1, 1, 346.5, 378.0,
    4, 1, 0, 229.5, 243.0,
    4, 1, 1,   0.0,  13.5,
    5, 4, 0,   0.0,  23.5,
    5, 7, 2, 193.5, 216.0,
    6, 1, 1, 166.5, 193.5
  ]