# Cut values for different run periods
clas12::ZVertexFilter:

  # default cuts
  - default:
    cuts: [ -1.5, 1.3 ]

  # RG-A fall2018 inbending
  - runs: [ 4760, 5419 ]
    cuts: [ -0.5, 0.5 ]

  # RG-A fall2018 outbending
  - runs: [ 5420, 5674 ]
    cuts: [ -0.8, 0.7 ]
