algorithm:
  name: 'clas12::FiducialFilter'

actions:
  - name: FilterRgaPass1
    type: filter
    inputs:
      - { name: pcal_sector, type: int }
      - { name: pcal_lv, type: float }
      - { name: pcal_lw, type: float }
      - { name: dc_sector, type: int }
      - { name: dc_r1x, type: float }
      - { name: dc_r1y, type: float }
      - { name: dc_r1z, type: float }
      - { name: dc_r2x, type: float }
      - { name: dc_r2y, type: float }
      - { name: dc_r2z, type: float }
      - { name: dc_r3x, type: float }
      - { name: dc_r3y, type: float }
      - { name: dc_r3z, type: float }
      - { name: torus, type: float }
      - { name: pid, type: int }
  - name: FilterPcalHomogeneous
    type: filter
    inputs:
      - { name: sector, type: int }
      - { name: lv, type: float }
      - { name: lw, type: float }
      - { name: torus, type: float }
      - { name: pid, type: int }
  - name: FilterDcXY
    type: filter
    inputs:
      - { name: sector, type: int }
      - { name: r1x, type: float }
      - { name: r1y, type: float }
      - { name: r1z, type: float }
      - { name: r2x, type: float }
      - { name: r2y, type: float }
      - { name: r2z, type: float }
      - { name: r3x, type: float }
      - { name: r3y, type: float }
      - { name: r3z, type: float }
      - { name: torus, type: float }
      - { name: pid, type: int }
  - name: FilterDcThetaPhi
    type: filter
    inputs:
      - { name: sector, type: int }
      - { name: r1x, type: float }
      - { name: r1y, type: float }
      - { name: r1z, type: float }
      - { name: r2x, type: float }
      - { name: r2y, type: float }
      - { name: r2z, type: float }
      - { name: r3x, type: float }
      - { name: r3y, type: float }
      - { name: r3z, type: float }
      - { name: torus, type: float }
      - { name: pid, type: int }
