algorithm:
  name: 'clas12::LorentzTransformer'

actions:

  - name: Boost
    type: transformer
    inputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: E
        type: double
        cast: float
      - name: beta_x
        type: double
      - name: beta_y
        type: double
      - name: beta_z
        type: double
    outputs:
      - name: px
        type: double
        cast: float
      - name: py
        type: double
        cast: float
      - name: pz
        type: double
        cast: float
      - name: E
        type: double
        cast: float
