name: Formatting

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  clang_format:
    name: Check C++ Formatting
    runs-on: ubuntu-latest
    steps:
      - name: check formatting
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: 16
          exclude-regex: 'examples/build_with_.*/.*\.cc'
