name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    tags: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dispatch:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
    uses: ./.github/workflows/ci.yml
    with:
      runner: ${{ matrix.runner }}
